apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecretKey }}
  jwt_secret_key: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  {{- else if .Values.global }}
  jwt_secret_key: {{ .Values.global.jwtSecretKey | b64enc | quote }}
  {{- end }}
