image:
  repository: todo-backend
  tag: final
  pullPolicy: IfNotPresent

env:
  - name: PORT
    value: "8080"
  - name: DATABASE_URL
    value: "postgresql://todo_user:todo_password@todo-app-postgresql:5432/todo_db"
  - name: JWT_SECRET_KEY
    value: "sk_prod_jwt_1234567890abcdefghijklmnopqrstuvwxyz"

secrets:
  jwtSecretKey: "sk_prod_jwt_1234567890abcdefghijklmnopqrstuvwxyz"
