apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: default
type: Opaque
data:
  BETTER_AUTH_SECRET: c2tfcHJvZF8xMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
  BETTER_AUTH_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
